### ISSUE TITLE
Question for code understanding: string handling for genregroups 

### ISSUE THREAD

**Issue by chincheta0815** [CDrummond/bliss-mixer#1]
Hej,

sorry for bothering, but I am trying to understand the string handling for genre groups.

I found line https://github.com/chincheta0815/bliss-mixer/blob/0ddc7b5bec868c0fbd94e7b0b28ef56a7d877f9d/src/api.rs#L157 in the bliss-mixer.

As far as I understand, this line should be responsible for comparing the genregroup  entry with the genre tag of the focused track.

If says: when the entry in the genre group, e.g. Rock is contained in the meta tag of the track, then set it as usable an use it.

So here my thought:
-> genre group contains "Latin" (= genre)
-> track meta tag contains: "Latin Rock" (=track_genres)
Coming to the line "track_genres.contains(genre)" I thought the track should be selected.
What am I doing wrong in my thinking?

**Comment by CDrummond** [comment]
No, the groups are a set of strings. "Latin" != "Latin Rock"
